### List Recap

-  Powerful
-  Collection of values
-  Hold different types
-  Change Add, Remove


### Major Drawback in List & Main reason for Numpy

-  Mathematical operation over collections
-  Speed

In [9]:
height = [1.73, 1.68, 1.71, 1.89, 1.79] # LIST 1
print(height)

weight = [65.4, 59.2, 63.6, 88.4, 68.7] # lIST 2
print(weight)

# Measure BMI
weight / height ** 2  # OUTPUT WITH TYPE ERROR

[1.73, 1.68, 1.71, 1.89, 1.79]
[65.4, 59.2, 63.6, 88.4, 68.7]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

<b>in the previous example its very hard to calculate BMI & we need to calculate BMI Individualy . It will take more time </b>

### Numpy :-Solution for previous Type Error

-  Numeric python
-  Alternative to python list : NumpyArray
-  calculation over entire Array
-  Easy & Fast
-  Installation :- 
   -  <code>pip install numpy</code>

In [8]:
! pip list

Package                            Version   
---------------------------------- ----------
alabaster                          0.7.10    
anaconda-client                    1.6.14    
anaconda-navigator                 1.9.6     
anaconda-project                   0.8.2     
asn1crypto                         0.24.0    
astroid                            1.6.3     
astropy                            3.0.2     
attrs                              18.1.0    
Babel                              2.5.3     
backcall                           0.1.0     
backports.shutil-get-terminal-size 1.0.0     
beautifulsoup4                     4.6.0     
bitarray                           0.8.1     
bkcharts                           0.2       
blaze                              0.11.3    
bleach                             2.1.3     
bokeh                              0.12.16   
boto                               2.48.0    
Bottleneck                         1.2.1     
certifi                           

<b>Already Numpy Install</b>

#### Now come to Solution & why Numpy is required over List

In [16]:
import numpy as np

height = [1.73, 1.68, 1.71, 1.89, 1.79] # LIST 1
weight = [65.4, 59.2, 63.6, 88.4, 68.7] # lIST 2


np_height = np.array(height) # convert into numpy from list
print(np_height)

np_weight = np.array(weight) # convert into numpy from list
print(np_weight)

# Now calculate bmi
bmi = np_weight / np_height **2
bmi

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

#### Numpy : Limitation & Remarks

-  only one type of data either float, int, bool , str & others
-  bcoz numpy is another python objects so have own methods 

<b>One difference between method of list & Numpy</b> 

In [20]:
# list example 
python_list = [1, 2, 3]

print(python_list + python_list)  # See 1st output for same method for addition


# Numpy Example with same 
numpy_array = np.array(python_list)
print( numpy_array + numpy_array) # See 2nd output for same method for addition

[1, 2, 3, 1, 2, 3]
[2 4 6]


## Numpy Subsetting

In [28]:
print(bmi) # prevously we calculated bmi

print(bmi[1]) # individual output from numpy array
print(bmi[3]) # individual output from numpy array

bmi > 23 # output in boolean



[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
20.97505668934241
24.74734749867025


array([False, False, False,  True, False])

In [29]:
bmi[bmi>23] #only one value, bmi of bmi values in array greater than 23 that we got bool value true in previous example 

array([24.7473475])

In [30]:
bmi[bmi> 21] # Same way 4 value 

array([21.85171573, 21.75028214, 24.7473475 , 21.44127836])

In [34]:
bmi[1:3] # bmi for 1st & 2nd exclude 3rd

array([20.97505669, 21.75028214])

#### Exercise : Your first numpy array

In [35]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [47]:
height_in = [74,74, 72,72, 73,69,69, 71,76,71, 73, 73, 74,74,69,70, 73, 75, 78, 79, 76,74,76,72,71,75,77,74,73,74]

# height is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)  # converted inches into meters

[74 74 72 72 73 69 69 71 76 71 73 73 74 74 69 70 73 75 78 79 76 74 76 72
 71 75 77 74 73 74]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542 1.905  1.9812 2.0066
 1.9304 1.8796 1.9304 1.8288 1.8034 1.905  1.9558 1.8796 1.8542 1.8796]


In [48]:
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 
             195, 180, 192, 225, 203, 195, 182, 188]
print(weight_lb)


[180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188]


#### Exercise : Baseball player's BMI

In [51]:
# height and weight are available as regular lists
# height_in & weight_lb previously given

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254 # inches to meter

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592 # pound to kilogram

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

[23.11037639 27.60406069 28.48080465 28.48080465 24.80333518 25.99036864
 30.86356276 27.89402921 28.11789135 25.10462629 24.80333518 23.7478741
 23.75233129 20.54255679 26.58105883 26.54444207 24.93526781 23.12315842
 25.30771077 25.91025019 24.95310704 29.52992539 23.73588231 24.41211827
 26.77826804 28.12276025 24.07202028 25.03624109 24.01173937 24.13750423]


#### Exercise : Lightweight baseball players


In [3]:
# height and weight are available as a regular lists

height_in = [74,74, 72,72, 73,69,69, 71,76,71, 73, 73, 74,74,69,70, 73, 75, 78, 79, 76,74,76,72,71,75,77,74,73,74]
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 
             195, 180, 192, 225, 203, 195, 182, 188]


# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21 
# light[light]

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])
# print(bmi[bmi < 21])

[False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False]
[20.54255679]


#### Exercise :- NumPy Side Effects

In [5]:
import numpy as np
print(np.array([True, 1, 2]) + np.array([3, 4, False]))

[4 5 2]


In [9]:
import numpy as np
print(np.array([True, 1, 2, 3, 4, False])) # 1st
print(np.array([4,3,0]) + np.array([0,2,2])) # 2nd
print(np.array([0, 1, 2, 3, 4, 5])) # 3rd
print(np.array([1,1,2]) + np.array([3,4,-1])) # 4th


#  Solution :- Right answer match with 2nd 

[1 1 2 3 4 0]
[4 5 2]
[0 1 2 3 4 5]
[4 5 1]


#### Exercise : Subsetting NumPy Arrays

In [9]:
import numpy as np

weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 
             195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199,  200, 215, 200, 205, 
             206, 186, 188, 220]
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 
              71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77]
 

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 30
print(np_weight_lb[30])

# Print out sub-array of np_height_in: index 10 up to and including index 20
print(np_height_in[10 :21])

200
[73 73 74 74 69 70 73 75 78 79 76]


### 2D Numpy Array

-  N-Dimensional Array
-  2-Dimensional Array
-  3-Dimensional Array

In [11]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

# Type of Array

print(type(np_height))  # N-Dimensional Array
print(type(np_weight))  # N-Dimensional Array

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


##### 2D Numpy Array Example

In [29]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

print(type(np_2d))  # Type of Array
print(np_2d)  # value of variable
print(type(np_2d[1][1]))

<class 'numpy.ndarray'>
[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
<class 'numpy.float64'>


### Shape of Array

In [20]:
print(np_2d.shape)  # output :- (2,5) 2 represent row & 5 column

(2, 5)


In [30]:
np_trial = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                     [65.4, 59.2, 63.6, 88.4, "68.7"]]) 

print(np_trial)
print(type(np_trial))
print(type(np_trial[1][1])) # Single type 

[['1.73' '1.68' '1.71' '1.89' '1.79']
 ['65.4' '59.2' '63.6' '88.4' '68.7']]
<class 'numpy.ndarray'>
<class 'numpy.str_'>


#### Positining of Array

#### Subsetting of 2D Numpy Array

In [37]:
np_trial = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                     [65.4, 59.2, 63.6, 88.4, 68.7]]) 


# 1st Row 
print(np_trial[0])

# 2nd Row
print(np_trial[1])

# 1st(index = 0) Row & 3rd Column(index = 2) :- 1st way
print(np_trial[0][2])

# 1st(index = 0) Row & 3rd Column(index = 2) :- 2nd Way
print(np_trial[0,2])

#Row before comma(: means include index 0 & exclude nothing),Column after comma(1:3 means include index 1 & exclude index 3)
print(np_trial[:,1:3])

#Row 2nd (index =1) , Column (every)
print(np_trial[1,:])

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


### Exercise :- Your First 2D NumPy Array

In [38]:
# Create baseball, a list of lists , Every raw contains height & width
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


#### Exercise :- Baseball data in 2D form

In [46]:
# baseball is available as a regular list of lists

baseball = [[74, 180],
            [74, 215],
            [72, 210],
            [72, 210],
            [73, 188],
            [69, 176],
            [69, 209],
            [71, 200],
            [76, 231],
            [71, 180],
            [73, 188],
            [73, 180],
            [74, 185],
            [74, 160],
            [69, 180],
            [70, 185],
            [73, 189],
            [75, 185],
            [78, 219],
            [79, 230]]

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)
print(np_baseball[1][0])
print(np_baseball[1, 0])

(20, 2)
74
74


#### Exercise :- Subsetting 2D Numpy Arrays

In [47]:
# baseball is available as a regular list of lists
baseball = [[74, 180],
            [74, 215],
            [72, 210],
            [72, 210],
            [73, 188],
            [69, 176],
            [69, 209],
            [71, 200],
            [76, 231],
            [71, 180],
            [73, 188],
            [73, 180],
            [74, 185],
            [74, 160],
            [69, 180],
            [70, 185],
            [73, 189],
            [75, 185],
            [78, 219],
            [79, 230]]

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 11th row of np_baseball
print(np_baseball[10,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]
# print(np_weight_lb)
# Print out height of 18th player
print(np_baseball[17,0])


[ 73 188]
75


#### Arithmetics of Numpy Array ( +, * )

In [53]:
mat = [[1, 2],
       [3, 4],
       [5, 6]]

import numpy as np
np_mat = np.array(mat)
print(np_mat)

# Multiplication 
np_mat_mul = np_mat * 2
print(np_mat_mul)

# Addition 
np_mat_add = np_mat + np.array([9,8])
print(np_mat_add)

# Addition Same Array
np_mul_add1 = np_mat + np_mat
print(np_mul_add1)

[[1 2]
 [3 4]
 [5 6]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[10 10]
 [12 12]
 [14 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


#### Exercise : 2D Arithmetic

In [57]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array
baseball = [[74.0, 180.0, 22.99],
            [74.0, 215.0, 34.69],
            [72.0, 210.0, 30.78],
            [72.0, 210.0, 35.43],
            [73.0, 188.0, 35.71],
            [69.0, 176.0, 29.39],
            [69.0, 209.0, 30.77],
            [71.0, 200.0, 35.07],
            [76.0, 231.0, 30.19],
            [71.0, 180.0, 27.05],
            [73.0, 188.0, 23.88],
            [74.0, 185.0, 23.29]]

updated = np.array([[  1.2303559 , -11.16224898,   1.        ],
                    [  1.02614252,  16.09732309,   1.        ],
                    [  1.1544228 ,   5.08167641,   1.        ],
                    [  1.09349925,   4.23890778,   1.        ],
                    [  0.82285669, -17.78200035,   1.        ],
                    [  0.99484223,   8.14402711,   1.        ],
                    [  1.2303559 , -11.16224898,   1.        ],
                    [  1.02614252,  16.09732309,   1.        ],
                    [  1.1544228 ,   5.08167641,   1.        ],
                    [  1.09349925,   4.23890778,   1.        ],
                    [  0.82285669, -17.78200035,   1.        ],
                    [  0.99484223,   8.14402711,   1.        ]])
 
# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 75.2303559  168.83775102  23.99      ]
 [ 75.02614252 231.09732309  35.69      ]
 [ 73.1544228  215.08167641  31.78      ]
 [ 73.09349925 214.23890778  36.43      ]
 [ 73.82285669 170.21799965  36.71      ]
 [ 69.99484223 184.14402711  30.39      ]
 [ 70.2303559  197.83775102  31.77      ]
 [ 72.02614252 216.09732309  36.07      ]
 [ 77.1544228  236.08167641  31.19      ]
 [ 72.09349925 184.23890778  28.05      ]
 [ 73.82285669 170.21799965  24.88      ]
 [ 74.99484223 193.14402711  24.29      ]]
[[  1.8796    81.64656   22.99    ]
 [  1.8796    97.52228   34.69    ]
 [  1.8288    95.25432   30.78    ]
 [  1.8288    95.25432   35.43    ]
 [  1.8542    85.275296  35.71    ]
 [  1.7526    79.832192  29.39    ]
 [  1.7526    94.800728  30.77    ]
 [  1.8034    90.7184    35.07    ]
 [  1.9304   104.779752  30.19    ]
 [  1.8034    81.64656   27.05    ]
 [  1.8542    85.275296  23.88    ]
 [  1.8796    83.91452   23.29    ]]


### NumPy: Basic Statistics

-  Data Analysis
   -  Get to know about your data
   -  Little Data -> Simply look it
   -  Big Data -> ??????
   
   
- Numpy Functions
  -  <code>np.mean(np_array[0:2,3:5])</code>
  -  <code>np.median(np_array[0:2,3:5])</code>
  -  <code>np.std(np_array[0:2,3:5])</code>
  -  <code>np.corrcoef(np_array[0:2,3:5], np_array[0:1,5])</code>




#### Exercise : Average versus median


In [65]:

# Import numpy
import numpy as np

np_baseball = np.array([[74.0, 180.0, 22.99],
                        [74.0, 215.0, 34.69],
                        [72.0, 210.0, 30.78],
                        [72.0, 210.0, 35.43],
                        [73.0, 188.0, 35.71],
                        [69.0, 176.0, 29.39],
                        [69.0, 209.0, 30.77],
                        [71.0, 200.0, 35.07],
                        [76.0, 231.0, 30.19],
                        [71.0, 180.0, 27.05],
                        [73.0, 188.0, 23.88],
                        [74.0, 185.0, 23.29]])
# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

72.33333333333333
72.5


#### Exercise :- Explore the baseball data

In [66]:


# Import numpy
import numpy as np

np_baseball = np.array([[74.0, 180.0, 22.99],
                        [74.0, 215.0, 34.69],
                        [72.0, 210.0, 30.78],
                        [72.0, 210.0, 35.43],
                        [73.0, 188.0, 35.71],
                        [69.0, 176.0, 29.39],
                        [69.0, 209.0, 30.77],
                        [71.0, 200.0, 35.07],
                        [76.0, 231.0, 30.19],
                        [71.0, 180.0, 27.05],
                        [73.0, 188.0, 23.88],
                        [74.0, 185.0, 23.29]])

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 72.33333333333333
Median: 72.5
Standard Deviation: 2.0138409955990952
Correlation: [[1.         0.33568045]
 [0.33568045 1.        ]]


#### Exercise :- Blend it all together

In [68]:
# heights and positions are available as lists

# Import numpy
import numpy as np

positions = ['GK',
             'M',
             'A',
             'D',
             'M',
             'D',
             'M',
             'M',
             'M',
             'A']

heights = [180,
           187,
           181,
           183,
           183,
           180,
           185,
           178,
           177,
           183]
 

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)


# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 180.0
Median height of other players: 183.0
